language: swift
xcode_scheme: TravisTest
osx_image: xcode11.1

before_install:
- bundle install

script:
- fastlane ci

after_success:
  # generate docs
- jazzy --xcodebuild-arguments -scheme,TravisTest --module TravisTest --source-directory TravisTest --readme README.md

deploy:
  provider: pages:git
  skip_cleanup: true
  token: $GITHUB_TOKEN
  keep_history: true
  local_dir: docs
  on:
    branch: master