language: swift
xcode_scheme: TravisTest
osx_image: xcode11.1

before_install:
- bundle install

script:
- fastlane ci
- bundle exec danger

after_success:
  # generate docs
- jazzy --xcodebuild-arguments -scheme,TravisTest --module TravisTest --source-directory TravisTest --readme README.md

deploy:
  provider: pages
  skip_cleanup: true
  token: $GITHUB_TOKEN
  local_dir: docs
  on:
    branch: master