# Import base_config from git
import_from_git(url: 'https://github.com/rakutentech/ios-buildconfig.git')

default_platform(:ios)

platform :ios do
  desc "Build everything"
  lane :ci do |options|
    xcversion(version: "~> 11.1")
  end
end